### ISSUE TITLE
Error with img.new_from_enum("[access=sequential]") and op.find_trim

### ISSUE THREAD

**Issue by a3mar** [akash-akya/vix#120]
When using Vix.Vips.Image.new_from_enum("[access=sequential]") and Vix.Vips.Operation.find_trim() on that image, i got error:
```
(process:9605): VIPS-WARNING **: 13:03:14.316: error in tile 0 x 896
(process:9605): VIPS-WARNING **: 13:03:14.316: error in tile 0 x 904 
** (Vix.Vips.Image.Error) Failed to write to target
    (vix 0.22.0) lib/vix/vips/image.ex:568: anonymous fn/1 in Vix.Vips.Image.write_to_stream/2
    (elixir 1.14.2) lib/stream.ex:1623: Stream.do_resource/5                                                                                                                             
    (elixir 1.14.2) lib/enum.ex:4307: Enum.map/2                                                                                                                                         
    iex:7: (file)
```

Example code to reproduce:
```elixir
{:ok, img} =
  File.stream!("/path/to/file.jpg", [], 2048)
  |> Vix.Vips.Image.new_from_enum("[access=sequential]")

{:ok, {_left, top, _width, height}} = Vix.Vips.Operation.find_trim(img, threshold: 5.0)

{:ok, area} = Vix.Vips.Operation.extract_area(img, 0, top, Vix.Vips.Image.width(img), height)

Vix.Vips.Image.write_to_stream(area, ".jpg")
|> Enum.map(fn chunk -> [chunk] end)
```

There is no error if remove "[access=sequential]", but other ops performance significantly degraded. 

I'm using 
elixir 1.14.2
erlang 25.3.2.2
vix 0.22.0 (bundled libvips)

**Comment by akash-akya** [comment]
```
{:ok, img} =
  File.stream!("/path/to/file.jpg", [], 2048)
  |> Vix.Vips.Image.new_from_enum("[access=sequential]")
```

Any specific reason for using the `new_from_enum`? 
`new_from_file` is better in this case, `Vix.Vips.Image.new_from_file("/path/to/file.jpg[access=sequential]")`. You can also use [`jpegload`](https://hexdocs.pm/vix/Vix.Vips.Operation.html#jpegload/2) if you know the input image is always going to be jpeg.

**Comment by a3mar** [comment]
Thank you for answer, this code is just example, in real project i trying to stream image from http response body. 

I tried to debug this situation, looks like this is some NIF magic, unfortunately, i have no experience with it.  Same code with ruby-vips works good

**Comment by akash-akya** [comment]
Understood, I'll take a look into the issue

**Comment by akash-akya** [comment]
@a3mar the issue seems to be that the image is opened as sequential is intended to be read only once. 
In this case `find_trim` eagerly reading the image, and again we are reading while writing to a stream (extract-area operation is lazy so that is not an issue).

Btw, you can stream the image without using `sequential` mode, libvips keep bit larger tile cache but it works. 

Can you share the ruby-vips code you used to test in which this is working?

**Comment by a3mar** [comment]
Hmm, sorry, my mistake, in ruby does not work too, i missed small part of code where access mode defines for exactly one operation in my app 🤯

Thank you for help and sorry.

**Comment by LostKobrakai** [comment]
I've been running into the same error trying to build a plug to resize images on the fly. @akash-akya can you go into a bit more detail on the issue you've described?

**Comment by akash-akya** [comment]
@LostKobrakai I forgot details, but root issue is that streamed image can only be read once sequentially. In the above example it is attempting to read twice which cause the second operation to fail.

* first time it is read by `find_trim` operation. This operation force the stream to read full image
* second time by `write` operation. This fails since the stream is already read.

> resize images on the fly
Can you share what are the operations you are using for this? Is it just single resize operation?

**Comment by LostKobrakai** [comment]
This is essentially what I'm doing:
```elixir
{:ok, image} = Image.from_binary(conn.assigns.source)
{width, height, _} = Image.shape(image)
[…]
image =
  Image.thumbnail!(
    image,
    size_and_dimensions_to_thumbnail({a, b}, {width, height}),
    opts
  )
image
|> Image.stream!(opts ++ [buffer_size: 5_242_880])
|> Enum.into(<<>>) # meant to stream chunks over http eventually
```
The strange part is that it doesn't fail everywhere, but only in some cases, for which I don't yet know how they're different.
