### ISSUE TITLE
[regression] dzsave missing since 0.19

### ISSUE THREAD

**Issue by akiroz** [akash-akya/vix#124]
Comparing the documentation between 0.18 and 0.19, it seems like the following functions are missing:
- `Vix.Vips.Operation.dzsave`
- `Vix.Vips.Operation.dzsave!`
- `Vix.Vips.Operation.dzsave_buffer`

Upon inspecting the [changes](https://github.com/akash-akya/vix/compare/v0.18.0...v0.19.0) it appears to be a minor version bump for libvips but the newer libvips version (8.14.2) still has the functions `vips_dzsave` and `vips_dzsave_buffer`.

Would it be possible to give me some pointers for how the vix functions are generated from libvips?

**Comment by akash-akya** [comment]
@akiroz, It is removed from the upstream due to license incompatibility.
More details here - https://github.com/lovell/sharp-libvips/pull/178. 
I should have mentioned the breaking changes in the changelog.


One way to fix this is installing the libvips yourself and setting env var
`export VIX_COMPILATION_MODE=PLATFORM_PROVIDED_LIBVIPS`.
Then vix will build new NIF using the libvips from the host machine

**Comment by akash-akya** [comment]
Closing the issue, let me know if you face any issue or need more information
