### ISSUE TITLE
Default background/vspacing/hspacing for Operation.arrayjoin in docs is incorrect

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#141]
The help docs for the options `:background`, `:vspacing` and `:hspacing`  are not aligned to the online docs and also not aligned to the actual behaviour.

```elixir
iex> h Vix.Vips.Operation.arrayjoin
....
## Optional

  • vspacing - Vertical spacing between images. Default: 1
  • hspacing - Horizontal spacing between images. Default: 1
  • background - Colour for new pixels. Default: nil
  ...
```
However the online docs for libvips say:
```
Each input image is placed with a box of size hspacing by vspacing pixels and cropped. These default to the largest width and largest height of the input images.

Space between images is filled with background . This defaults to 0 (black).
```
The online docs and the actual behaviour appear to align as expected.  Unfortunately there isn't really a default value for `:hspacing` and `:vspacing`. They need to be omitted for them to be correctly calculated.

**Comment by akash-akya** [comment]
Hi @kipcole9, unfortunately those are the default values [libvips specify](https://github.com/libvips/libvips/blob/40865440a59c0ec53c1b1270f0b1e26bb1307362/libvips/conversion/arrayjoin.c#L422-L434). And libvips online document is different from the one it provides in the operation introspection. 

I guess it is like so because currently there is no way to specify `null` value as default value for an integer type.

Let me bring this up in libvips repo and see.

**Comment by kipcole9** [comment]
Akash, thanks, I figured that was probably the case.  I think there are a few other cases in `libvips` like this. Perhaps standardising on `-1` meaning "default behaviour" would be something for John/Klaus to consider for the future.
