### ISSUE TITLE
Segfault when calling `filename` on a "image_enum"

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#39]
When calling `Vix.Vips.Image.filename/1` on an image that was created from `Vix.Vips.Image.new_from_enum/1`, `libvips` segfaults.  This may well be an issue in `libvips` - if so I will try to open an issue there but I don't think my `C`-fu is strong enough to do that.

### Example
```elixir
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> stream = File.stream! "test/support/images/Kamchatka-2019-8754.jpg"        
%File.Stream{
  line_or_bytes: :line,
  modes: [:raw, :read_ahead, :binary],
  path: "test/support/images/Kamchatka-2019-8754.jpg",
  raw: true
}
iex(2)> {:ok, image} = Vix.Vips.Image.new_from_enum(stream)  
{:ok, %Vix.Vips.Image{ref: #Reference<0.4059742114.2826829856.241978>}}
iex(3)> Vix.Vips.Image.filename image
zsh: segmentation fault  iex -S mix
```

I wonder if a function to know if the `Vix.Vips.Image.t` is also a "streaming" image or not would be helpful? Some operations probably won't work well on streaming images and a function to introspect that would allow me to code defensively where required.

**Comment by akash-akya** [comment]
@kipcole9 thanks for reporting the issue. I'll check and report back.

Btw, it should be `File.stream!(filename, [], _some_number)` since default is `:line` which is not what we want. 
Anyway, I noticed that error happen in both cases, so thats not the issue.

**Comment by akash-akya** [comment]
Hi @kipcole9, issue is not specific to stream but more generic issue with handling of null g_value. 

I overlooked it previously because libvips [documents states](https://www.libvips.org/API/current/libvips-header.html#vips-image-get) that `vips_image_get_typeof` tells if field exists or not.
> This will return -1 and add a message to the error buffer if the field does not exist. Use [vips_image_get_typeof()](https://www.libvips.org/API/current/libvips-header.html#vips-image-get-typeof) to test for the existence of a field first if you are not certain it will be there.

But apparently we can still get NULL even after checking field using `vips_image_get_typeof`.

Anyway, it's fixed in master now. And rebased `vips-conn` branch as well.

> I wonder if a function to know if the Vix.Vips.Image.t is also a "streaming" image or not would be helpful? 

I'm not sure about this. I think it's better to just follow libvips on this. If libvips has functions which hints this, then we can expose those.

Thanks for the detailed issue description with easy steps to reproduce! segfaults are especially hard to reproduce and find
