### ISSUE TITLE
[Feature] Allow slices in Access behaviour

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#69]
`Nx` has a more [feature-rich implementation](https://github.com/elixir-nx/nx/blob/2eeb6178d2669a1b3f2bae83058a57c252f110b9/nx/lib/nx/tensor.ex#L37-L153) of the `Access` behaviour. In particular it allows slicing the matrix.  @cocoa-xu has done a [similar implementation in eVision](https://github.com/cocoa-xu/evision/blob/main/lib/evision_mat.ex#L438-L613) that I propose now also be implemented in `Vix`.

The implementation is backwards compatible with the current simple band extraction.  If you are in agreement, I will take an initial pass at implementation. There isn't any `nif` requirements so its probably within my skills :-)

Since all `Vix.Vips.Image.t` are 2-dimensional with variable number of bands, implementation can be quite a bit simpler than either `Nx` or `eVision` I believe.

**Comment by akash-akya** [comment]
This looks fantastic! I think this would make vix more in-line with Nx like interface. Which is great since the user does not have to learn anything new if they familiar with something already.

Please go ahead with the implementation 🙏🏼  
I think we can skip mutation operations for now, like `get_and_update`, which you already did previously.

If you are occupied, let me know :)

**Comment by kipcole9** [comment]
Have finished the implementation and tests. Just need to write some documentation updates and its ready for your review. Should be fine in the next 12 hours.  Been an intense week in the day job and the night job!

**Comment by akash-akya** [comment]
Addressed in #75

**Comment by akash-akya** [comment]
Addressed in https://github.com/akash-akya/vix/pull/75
